- src/utils/object.mapper.js
Signed-off-by: lysign <liu.ying@99cloud.net>
/kind bug
Fixes #15 
```
```
```release-note
```
```docs
```
> fix creating the cluster template, the version is empty

- src/components/StepForm/index.jsx
- src/components/StepForm/steps.jsx
- src/pages/cluster/components/PluginForm/index.jsx
- src/pages/cluster/components/PluginForm/storageFrom.jsx
- src/pages/cluster/components/Tips/index.jsx
- src/pages/cluster/containers/Cluster/actions/AddPlugin.jsx
- src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
- src/pages/cluster/containers/Cluster/actions/Create/Storage.jsx
- src/pages/cluster/containers/Cluster/actions/Create/index.jsx
- src/pages/cluster/containers/Template/cluster/actions/Create/Storage.jsx
- src/pages/cluster/containers/Template/plugin/actions/Create.jsx
- src/stores/cluster.js
Fixes #17 
```
```
```release-note
```
```docs
```
> fix: fix plugin step is empty when without plugin component when create cluster

- cypress/config/config.yaml
- src/components/StepForm/index.jsx
Fixes #29 
```
```
```release-note
```
```docs
```
> fix: fix err when click prev in last create cluster step

- src/components/StepForm/footer.jsx
- src/components/StepForm/index.jsx
- src/pages/cluster/containers/Cluster/actions/Create/index.jsx
/kind bug
Fixes #51 
```
```
```release-note
```
```docs
```
> fix createQuickly in create cluster

- src/pages/cluster/containers/Cluster/Detail/Backup/actions/Edit.jsx
- src/pages/cluster/containers/Cluster/actions/Backup.jsx
- src/utils/object.mapper.js
/kind bug
Fixes #55 
```
```
```release-note
```
```docs
```
> fix backup does not display the k8s version and edit backup

- src/pages/cluster/components/plugin/PluginForm.jsx
- src/utils/object.mapper.js
/kind bug
Fixes #57 
```
```
```release-note
```
```docs
```
> fix the plugin data is not cached after the  next step during create cluster

- src/pages/cluster/components/plugin/StorageForm.jsx
- src/pages/cluster/containers/Cluster/actions/AddStorage.jsx
/kind bug
Fixes #65 
```
```
```release-note
```
```docs
```
> After selecting the plugin template, the storage error has been opened

- src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx
/kind bug
Fixes #73 
```
```
```release-note
```
```docs
```
> fix the online locaregistry in the cluster details only displays 'online'

- src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
/kind bug
Fixes #79 
```
```
```release-note
```
```docs
```
> fix edit cluster template notification error

- .github/workflows/release.yml
Signed-off-by: lixd <xueduan.li@gmail.com>
/kind flake
update ci,upload to oss when add a tag.
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: update ci,upload to oss when add a tag.

- src/components/Tables/Base/ItemAction/index.jsx
- src/layouts/Base/index.jsx
- src/pages/cluster/containers/Cluster/actions/LinkAddPlugin.jsx
- src/stores/cluster.js
- src/stores/index.js
/kind bug
Fixes #89
```
```
```release-note
```
```docs
```
> fix: remove addplugin action when components no pligun

- src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
- src/utils/object.mapper.js
/kind bug
Fixes #76 
```
```
```release-note
```
```docs
```
> fix the image type can not be saved when saving cluster as a template

- src/components/FormItem/SelectCycle/index.jsx
- src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/actions/Edit.jsx
- src/resources/date.jsx
- src/utils/index.js
/kind bug
Fixes #110 
```
```
```release-note
```
```docs
```
> fix: scheduled backup weekly dictionary error

- src/components/Tables/Base/index.jsx
- src/containers/List/index.jsx
/kind bug
Fixes #107
```
```
```release-note
```
```docs
```
> fix sort by createtime is not work

- src/pages/cluster/components/plugin/uiSchemas.js
Fixes #
```
```
```release-note
```
```docs
```
> fix: hidden jwtSecret when clusterRole is member

- src/containers/List/index.jsx
/kind bug
Fixes #163 
```
```
```release-note
```
```docs
```
> fix: the list of footer select limit can not be selected

- src/components/Tables/Base/index.jsx
- src/locales/en.json
- src/locales/zh.json
- src/resources/cluster.jsx
/kind feature
Fixes #166 
```
```
```release-note
```
```docs
```
> feat: add expiration tag in cluster list

- src/components/Tables/Base/ActionButton/index.jsx
/kind bug
Fixes #183 
```
```
```release-note
```
```docs
```
> fix: the interface does not prompt information when deleting a cluster with backup

- config/webpack.prod.js
Signed-off-by: x893675 <x893675@icloud.com>
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: rewrite default git version command

- src/components/Tabs/index.less
/kind bug
Fixes #200 
```
```
```release-note
```
```docs
```
> fix: tip Incomplete display

- src/pages/cluster/containers/Cluster/actions/RemoveNodes.jsx
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: master node can not be selected

- src/pages/node/containers/Node/actions/Terminal.jsx
Fixes #
```
```
```release-note
```
```docs
```
> fix: terminal port can not string

- src/components/FormItem/IPGroup/index.jsx
Fixes #
```
```
```release-note
```
```docs
```
> refactor: refactor ipgroup component

- src/utils/regex.js
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: modify reg for path(add '-')

- src/locales/en.json
- src/locales/zh.json
- src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx
- src/utils/object.mapper.js
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: modify cluster detail with controlPlaneHealth

- src/pages/cluster/components/plugin/AddPlugin.jsx
- src/pages/cluster/components/plugin/PluginForm.jsx
- src/pages/cluster/containers/Cluster/Detail/Operation/index.jsx
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: use plugin template error & operaiton list cached by cluster detail

- src/locales/en.json
- src/locales/zh.json
- src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
- src/pages/cluster/containers/Cluster/Detail/Storage/index.jsx
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: plugin cannot be removed when cluster is no running

- src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: rancher healthy not displayed

- src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: calico saved failed in cluster template

- .github/workflows/front-e2e-test.yml
Signed-off-by: cmyscoups chen.mengyun@99cloud.net
> ci: add e2e check in workflow

- src/utils/index.js
- src/utils/index.test.js
Fixes #
```
```
```release-note
```
```docs
```
> fix: fix versionCross error

- tools/test_cases_associated.js
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: e2e summary resource

- cypress/support/e2e.js
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: e2e config resource

- config/webpack.dev.js
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: webpack dev support https

- cypress/support/resource.js
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: remove clearSearchInput in deletecluster(e2e)

- src/components/FormRender/index.jsx
- src/components/FormRender/widgets/SelectInput/index.jsx
- src/pages/cluster/components/plugin/uiSchemas.js
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: the storageclass form used by select or input

- src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/actions/Edit.jsx
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: format time for scheduledBackup

- config/webpack.e2e.js
- config/webpack.prod.js
Fixes #
```
```
```release-note
```
```docs
```
> fix: fix git no tag build err

- src/components/FormItem/index.jsx
- src/locales/en.json
- src/locales/zh.json
- src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
- src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
- src/pages/cluster/containers/Cluster/actions/Create/index.jsx
- src/pages/cluster/containers/Cluster/actions/Edit.jsx
- src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
- src/pages/cluster/containers/Template/cluster/actions/Create/Confirm.jsx
- src/utils/validate.js
/kind feature
Fixes #
```
```
```release-note
```
```docs
```
> feat: add external domain&domainPort for create cluster

- .github/workflows/release.yml
Fixes #
```
```
```release-note
```
```docs
```
> fix: add kube-console on release kc-console
