.github/workflows/buid.yaml
.github/workflows/e2e-test.yml
.github/workflows/release.yml
.github/workflows/unit-test.yml

Signed-off-by: lixd <xueduan.li@gmail.com>
/kind flake
add workflows.
Fixes #
```
```
```release-note
None
```
```docs
```

feat: add workflows.

---

src/components/Form/index.jsx
src/pages/cluster/containers/Template/cluster/actions/Delete.jsx
src/pages/cluster/containers/Template/plugin/actions/Create.jsx
src/styles/base.less
src/utils/object.mapper.js

Change-Id: Ib831d7ea3314a57bdbc4475dd3eb725dc0a29fd0
/kind bug
Fixes #6 
```
```
```release-note
```
```docs
```

fix cluster template deletion error

---

.github/workflows/commitlint.yml
docs/test.md

Fixes #10
```
```
```release-note
```
```docs
```

Add workflow action

---

src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
src/pages/cluster/containers/Cluster/Detail/Storage/index.jsx
src/pages/cluster/containers/Cluster/Detail/index.jsx
src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx

/kind bug
Fixes #12 
```
```
```release-note
None
```
```docs
```

fix cluster detail storage crad can be save as template

---

.eslintrc
config/webpack.common.js
jest.config.js
jsconfig.json
src/components/FormRender/widgets/KSPlugins/index.jsx
src/pages/cluster/containers/Cluster/actions/AddPlugin.jsx
src/pages/cluster/containers/Cluster/actions/Create/Plugin.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Plugin.jsx
src/pages/cluster/containers/Template/plugin/actions/Create.jsx

Fixes #21 
```
```
```release-note
```
```docs
```

fix: fix @ resolve path result in build err

---

src/pages/cluster/containers/Template/plugin/actions/Delete.jsx

Signed-off-by: lysign <liu.ying@99cloud.net>
/kind bug
Fixes #23 
```
```
```release-note
```
```docs
```

fix: plugin template deletion error

---

src/pages/cluster/components/plugin/PluginForm.jsx
src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx

Fixes #25 
```
```
```release-note
```
```docs
```

fix: fix plugin render loop

---

src/stores/base.js
src/stores/cluster.js

/kind bug
Fixes #27 
```
```
```release-note
```
```docs
```

fix file circular reference

---

src/stores/websocket.js

Fixes #31 
```
```
```release-note
```
```docs
```

fix: fix websocket url err

---

src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx
src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
src/pages/cluster/containers/Cluster/actions/Create/index.jsx
src/utils/object.mapper.js

/kind bug
Fixes #33 
```
```
```release-note
```
```docs
```

fix cluster structure change

---

src/stores/log.js

/kind bug
Fixes #37 
```
```
```release-note
```
```docs
```

fix the cluster log cannot be closed

---

src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
src/stores/cluster.js
src/utils/object.mapper.js

/kind bug
Fixes #41 
```
```
```release-note
```
```docs
```

fix plugin cannot be installed

---

src/pages/cluster/containers/Cluster/actions/Upgrade.jsx
src/utils/index.js

Issue: 143756
Fixes #45 
```
```
```release-note
```
```docs
```

fix: fix upgrade cluster check

---

src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Confirm.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
src/resources/cluster.jsx
src/resources/common.js
src/stores/cluster.js
src/utils/object.mapper.js

/kind bug
Fixes #47 
```
```
```release-note
```
```docs
```

fix modify template structure

---

src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
src/stores/cluster.js

/kind bug
Fixes #53 
```
```
```release-note
```
```docs
```

fix offline environment access online api page white screen

---

src/stores/base.js
src/stores/cluster.js
src/utils/object.mapper.js

Fixes #68 
```
```
```release-note
```
```docs
```

fix: fix cluster detail basic info not display master ip

---

src/stores/base.js

Fixes #68
```
```
```release-note
```
```docs
```

fix: fix base.js

---

src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
src/pages/cluster/containers/Cluster/Detail/Storage/index.jsx
src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
src/pages/cluster/containers/Template/plugin/actions/Create.jsx
src/utils/object.mapper.js

/kind bug
Fixes #63,#64,#66
```
```
```release-note
```
```docs
```

fix error saving parameters as template

---

src/containers/Action/ModalAction/index.jsx
src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/actions/Add.jsx

Fixes #62 
```
```
```release-note
```
```docs
```

fix: fix schedulebackup notify err

---

src/components/Form/index.jsx
src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/actions/Add.jsx
src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/actions/Edit.jsx
src/pages/cluster/containers/Cluster/actions/ScheduledBackup.jsx
src/resources/backup.jsx

/kind bug
Fixes #83 
```
```
```release-note
```
```docs
```

fix select month end error for scheduled backup

---

src/containers/Action/ConfirmAction/index.jsx
src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/Cluster/actions/LinkAddPlugin.jsx
src/pages/cluster/containers/Cluster/actions/LinkAddStorage.jsx
src/pages/cluster/containers/Cluster/actions/RemovePlugin.jsx
src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
src/pages/cluster/containers/Cluster/actions/ScheduledBackup.jsx

Fixes #
```
```
```release-note
```
```docs
```

fix: fix notify err when remove storage

---

src/stores/index.js
src/utils/request.js

/kind bug
Fixes #85 
```
```
```release-note
```
```docs
```

fix: refresh token does not match expires

---

src/core/menu.js
src/locales/basezh.json
src/pages/cluster/containers/BackupPoint/actions/Create.jsx
src/pages/cluster/containers/BackupPoint/actions/Delete.jsx
src/pages/cluster/containers/BackupPoint/actions/Edit.jsx
src/pages/cluster/containers/Cluster/actions/LinkAddPlugin.jsx
src/pages/cluster/containers/Cluster/actions/LinkAddStorage.jsx
src/pages/cluster/containers/Cluster/actions/Terminal.jsx
src/pages/cluster/containers/LocalRegistry/actions/Add.jsx
src/pages/cluster/containers/LocalRegistry/actions/Delete.jsx

Fixes #
```
```
```release-note
```
```docs
```

fix: fix role

---

src/utils/request.js

/kind bug
Fixes #93 
```
```
```release-note
None
```
```docs
```

fix: ahead of 10 minutes refresh token

---

src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
src/utils/object.mapper.js

Fixes #76
```
```
```release-note
None
```
```docs
```

fix: fix template offline field  error

---

.github/workflows/e2e-test.yml
.github/workflows/unit-test.yml

Signed-off-by: x893675 <x893675@icloud.com>
/kind flake
update workflow to enable upload test coverage in push event
Fixes #
```
```
```release-note
None
```
```docs
```

enable upload test coverage in push evnet

---

src/pages/cluster/components/plugin/PluginForm.jsx
src/pages/cluster/components/plugin/StorageForm.jsx
src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
src/pages/cluster/containers/Cluster/Detail/Storage/index.jsx
src/pages/cluster/containers/Cluster/Detail/index.jsx
src/pages/cluster/containers/Cluster/actions/AddPlugin.jsx
src/pages/cluster/containers/Cluster/actions/AddStorage.jsx
src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
src/pages/cluster/containers/Cluster/actions/Create/Plugin.jsx
src/pages/cluster/containers/Cluster/actions/Create/index.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Plugin.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Storage.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
src/pages/cluster/containers/Template/index.jsx
src/pages/cluster/containers/Template/plugin/actions/Create.jsx
src/stores/cluster.js
src/stores/index.js

/kind bug
Fixes #103 
```
```
```release-note
```
```docs
```

refactor remove cluster components and use global components

---

src/pages/cluster/containers/Cluster/Detail/Backup/actions/index.jsx

/kind feature
Fixes #113 
```
```
```release-note
```
```docs
```

feat: cluster backup add batch delete

---

src/components/StepForm/footer.jsx
src/components/StepForm/index.jsx
src/pages/cluster/components/plugin/PluginForm.jsx
src/pages/cluster/components/plugin/StorageForm.jsx
src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
src/pages/cluster/containers/Cluster/actions/Create/Storage.jsx
src/pages/cluster/containers/Cluster/actions/Create/index.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Confirm.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Storage.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx

/kind bug
Fixes #116 
```
```
```release-note
```
```docs
```

fix: error in the last step of cluster quick creation

---

src/stores/index.js
src/utils/request.js

Fixes #
```
```
```release-note
```
```docs
```

fix: fix token expire not redirect to login

---

src/pages/cluster/containers/Cluster/actions/Create/Node.jsx

/kind bug
Fixes #127 
```
```
```release-note
```
```docs
```

fix region default value

---

src/components/ErrorBoundary/index.jsx
src/core/App.jsx

Fixes #122 
```
```
```release-note
```
```docs
```

feat: add ErrorBoundary

---

src/hooks/index.js
src/hooks/useModal.js
src/locales/en.json
src/locales/zh.json
src/pages/oauth/containers/Login/Verification.jsx
src/pages/oauth/containers/Login/index.jsx
src/pages/oauth/containers/Login/index.less
src/stores/index.js

Fixes #101 
```
```
```release-note
```
```docs
```

feat: add login verification

---

src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
src/pages/cluster/containers/Cluster/actions/Create/index.jsx
src/pages/cluster/containers/Cluster/actions/Upgrade.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Confirm.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
src/resources/cluster.jsx
src/stores/cluster.js
src/utils/index.js
src/utils/object.mapper.js

/kind feature
Fixes #133 
```
```
```release-note
```
```docs
```

feat modify data structure of componentmeta interface

---

src/utils/request.js

Fixes #
```
```
```release-note
```
```docs
```

fix: fix request.js

---

src/components/FormItem/SelectForValue/index.jsx
src/components/FormItem/index.jsx
src/locales/en.json
src/locales/zh.json
src/pages/cluster/components/SelectNodes/List.jsx
src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
src/pages/cluster/containers/Cluster/actions/Create/index.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
src/stores/cluster.js
src/utils/index.js
src/utils/object.mapper.js

/kind feature
Fixes #140 
```
```
```release-note
```
```docs
```

feat filter cluster k8s version architecture according to nodes

---

src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/BackupPoint/actions/Create.jsx

/kind feature
Fixes #105 
```
```
```release-note
```
```docs
```

feat add backup rootdir tip

---

src/stores/index.js
src/utils/index.js

/kind bug
Fixes #142 
```
```
```release-note
```
```docs
```

fix oauth2 redirect & aouth2 login failed

---

src/stores/cluster.js

/kind bug
Fixes #150
```
```
```release-note
```
```docs
```

fix sort k8s version

---

src/hooks/useModal.js
src/pages/oauth/containers/Login/index.jsx

/kind bug
Fixes #151 
```
```
```release-note
```
```docs
```

fix login button loading

---

src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
src/resources/cluster.jsx

/kind bug
Fixes #154 
```
```
```release-note
```
```docs
```

fix modify cluaster IPv4 Autodetection Tip

---

src/locales/en.json
src/locales/zh.json
src/pages/oauth/containers/Login/Verification.jsx

Fixes #
```
```
```release-note
```
```docs
```

fix: fix i18n

---

src/pages/cluster/containers/Cluster/Detail/Operation/actions/PipelineLogDialog/LeftSteps.jsx
src/pages/cluster/containers/Cluster/Detail/Operation/actions/PipelineLogDialog/RightLogContent.jsx
src/pages/cluster/containers/Cluster/Detail/Operation/actions/PipelineLogDialog/index.jsx
src/pages/cluster/containers/Cluster/Detail/Operation/actions/PipelineLogDialog/index.less
src/stores/log.js
src/stores/operation.js

/kind feature
Fixes #160 
```
```
```release-note
```
```docs
```

feat  add auto open first log  and show latest in operation log

---

src/containers/Action/ConfirmAction/index.jsx
src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/Cluster/Detail/Storage/actions/RemovePlugin.jsx
src/pages/cluster/containers/Cluster/Detail/Storage/index.jsx

/kind bug
Fixes #168 
```
```
```release-note
```
```docs
```

fix: restrict removal of storage classes

---

src/components/Icon/index.jsx
src/components/Status/index.jsx
src/components/StatusReason/index.jsx
src/components/StatusReason/index.less
src/components/Tips/index.jsx
src/components/Tips/index.less
src/locales/basezh.json
src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/Cluster/actions/Backup.jsx
src/pages/cluster/containers/Cluster/actions/Delete.jsx
src/pages/cluster/containers/Cluster/actions/Edit.jsx
src/pages/cluster/containers/Cluster/actions/KubeConfig.jsx
src/pages/cluster/containers/Cluster/actions/LinkAddPlugin.jsx
src/pages/cluster/containers/Cluster/actions/LinkAddStorage.jsx
src/pages/cluster/containers/Cluster/actions/Reset.jsx
src/pages/cluster/containers/Cluster/actions/Restore.jsx
src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
src/pages/cluster/containers/Cluster/actions/ScheduledBackup.jsx
src/pages/cluster/containers/Cluster/actions/Terminal.jsx
src/pages/cluster/containers/Cluster/actions/UpdateLicense.jsx
src/pages/cluster/containers/Cluster/actions/Upgrade.jsx
src/utils/base64.js
src/utils/index.js
src/utils/object.mapper.js
src/utils/validate.js

Fixes #
```
```
```release-note
```
```docs
```

feat: add base64js and modify some utils、components

---

src/containers/Tab/trendsTab.jsx
src/pages/cluster/containers/Cluster/Detail/index.jsx

/kind bug
Fixes #173 
```
```
```release-note
```
```docs
```

fix: details page tabs customization

---

src/locales/en.json
src/locales/zh.json
src/resources/cluster.jsx

/kind feature
Fixes #175 
```
```
```release-note
```
```docs
```

feat: add cluster status locals(remove)

---

src/pages/cluster/containers/Cluster/Detail/Operation/actions/PipelineLogDialog/index.jsx

browser compatibility issues about function findlastindex with operation log loading
/kind bug
Fixes #179 
```
```
```release-note
```
```docs
```

fix: browser compatibility issues about function findlastindex with operation log loading

---

src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx

/kind bug
Fixes #181 
```
```
```release-note
```
```docs
```

fix: add validator in kubelet data dir

---

src/stores/index.js
src/stores/root.js

Reverts kubeclipper/console#189

Revert "perf: optimize import store"

---

src/components/CodeEditor/index.jsx
src/components/FormItem/YamlInput/index.jsx
src/components/FormItem/index.jsx
src/components/NotFound/index.jsx
src/core/menu.js
src/locales/en.json
src/locales/zh.json
src/pages/cluster/components/KubeConfig/index.less
src/pages/cluster/containers/Cluster/actions/index.jsx
src/pages/cluster/containers/Hosting/Cluster/actions/Add.jsx
src/pages/cluster/containers/Hosting/Cluster/actions/Remove.jsx
src/pages/cluster/containers/Hosting/Cluster/index.jsx
src/pages/cluster/containers/Hosting/index.jsx
src/pages/cluster/routes/index.js
src/utils/validate.js

Fixes #
```
```
```release-note
```
```docs
```

feat: add kubeadm hosting

---

src/pages/cluster/components/plugin/uiSchemas.js
src/utils/object.mapper.js

/kind feature
Fixes #194 
```
```
```release-note
```
```docs
```

feat: add nfs-csi support in cluster storage

---

src/components/Tables/Base/ItemAction/DropdownActions.jsx
src/containers/Tab/trendsTab.jsx
src/containers/TabDetail/index.jsx
src/pages/cluster/containers/Cluster/Detail/index.jsx
src/pages/cluster/containers/Cluster/actions/Delete.jsx
src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx
src/pages/cluster/containers/Cluster/actions/Upgrade.jsx
src/pages/cluster/containers/Cluster/actions/index.jsx
src/pages/cluster/containers/Hosting/Detail/Clusters/index.jsx
src/pages/cluster/containers/Hosting/Detail/index.jsx
src/pages/cluster/containers/Hosting/actions/Create.jsx
src/pages/cluster/containers/Hosting/actions/Edit.jsx
src/pages/cluster/containers/Hosting/actions/Remove.jsx
src/pages/cluster/containers/Hosting/actions/Sync.jsx
src/pages/cluster/containers/Hosting/actions/index.jsx
src/pages/cluster/containers/Hosting/actions/index.less
src/pages/cluster/containers/Hosting/index.jsx
src/pages/cluster/routes/index.js
src/stores/cloudprovider.js
src/stores/root.js
src/utils/form.templates.js
src/utils/index.js
src/utils/object.mapper.js

Fixes #
```
```
```release-note
```
```docs
```

feat: add kubeadm provider

---

src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx

/kind bug
Fixes #2
```
```
```release-note
```
```docs
```

fix: modify cluster name validate message

---

jest.config.js
src/utils/base64.js
src/utils/base64.test.js
src/utils/localStorage.test.js
src/utils/validate.js
src/utils/validate.test.js

Fixes #
```
```
```release-note
```
```docs
```

feat: add unit case

---

src/components/Tabs/index.jsx
src/components/Tabs/index.less
src/locales/en.json
src/locales/zh.json

/kind bug
Fixes #204 
```
```
```release-note
```
```docs
```

feat: add deprecated tip in plugin

---

src/components/Tables/Base/index.jsx
src/containers/List/index.jsx
src/pages/access/containers/Role/Detail/AuthorizedUsers/index.jsx
src/pages/access/containers/Role/index.jsx
src/pages/access/containers/User/index.jsx
src/pages/cluster/containers/BackupPoint/index.jsx
src/pages/cluster/containers/Cluster/Detail/Operation/index.jsx
src/pages/cluster/containers/Cluster/index.jsx
src/pages/cluster/containers/Hosting/Cluster/index.jsx
src/pages/cluster/containers/Hosting/Detail/Clusters/index.jsx
src/pages/cluster/containers/Hosting/index.jsx
src/pages/cluster/containers/Template/cluster/index.jsx
src/pages/cluster/containers/Template/plugin/index.jsx
src/pages/region/containers/Region/Detail/ClusterList/index.jsx
src/pages/region/containers/Region/index.jsx
src/resources/backup.jsx
src/utils/index.js

Fixes #
```
```
```release-note
```
```docs
```

feat: add fuzzy search for table

---

cypress.json
cypress/config/config.yaml
cypress/integration/pages/login.spec.js
cypress/support/index.js

/kind feature
Fixes #211 
```
```
```release-note
```
```docs
```

feat: add login in e2e test

---

src/components/Tables/Base/ItemAction/index.less
src/pages/cluster/containers/Cluster/actions/Delete.jsx
src/pages/cluster/containers/Cluster/actions/Terminal.jsx
src/pages/cluster/containers/Cluster/actions/index.jsx

/kind bug
Fixes #191
```
```
```release-note
```
```docs
```

perf: optimize cluster operation tab

---

src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/Cluster/actions/Registry.jsx

Fixes #
```
```
```release-note
```
```docs
```

fix: modidy update registry msg

---

src/pages/node/containers/Node/index.jsx
src/utils/object.mapper.js

Fixes #
```
```
```release-note
```
```docs
```

fix: fix ip search in node table

---

src/containers/List/index.jsx
src/utils/index.js

Fixes #
```
```
```release-note
```
```docs
```

fix: fix log search

---

src/pages/cluster/containers/Cluster/actions/Registry.jsx

Fixes #
```
```
```release-note
```
```docs
```

fix: fix cluster registry cannot be empty

---

cypress.config.js
cypress/e2e/pages/cluster/backup.cy.js
cypress/e2e/pages/cluster/cluster.cy.js
cypress/support/commands.js
cypress/support/form-commands.js
cypress/support/table-commands.js

/kind feature
Fixes #
```
```
```release-note
```
```docs
```

feat: add e2e about backup

---

src/pages/cluster/containers/Cluster/Detail/NodesList/actions/Add.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: node list error in cluster detail

---

cypress.config.js
cypress/e2e/pages/cluster/backup.cy.js
cypress/e2e/pages/cluster/detail.cy.js
cypress/support/form-commands.js
src/pages/cluster/components/plugin/AddPlugin.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: add plugin can not be confirm 

---

src/pages/cluster/containers/Cluster/Detail/ScheduledBackup/index.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: scheduled backup can not be sort by create time

---

src/locales/zh.json

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: modify locals

---

src/pages/cluster/containers/BackupPoint/actions/Create.jsx
src/pages/cluster/containers/BackupPoint/actions/Edit.jsx
src/utils/object.mapper.js

Fixes #
```
```
```release-note
```
```docs
```

fix: modify struct for backup space description

---

src/components/StatusReason/index.less

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: modify styles for status reason

---

cypress.config.js
cypress/e2e/pages/cluster/backup.cy.js
cypress/e2e/pages/cluster/detail.cy.js
cypress/e2e/pages/cluster/upgrade.cy.js
cypress/support/commands.js

/kind feature
Fixes #
```
```
```release-note
```
```docs
```

feat: add e2e about upgrade cluster

---

src/containers/BaseDetail/index.jsx
src/containers/Tab/trendsTab.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: detail info cannot be catched

---

src/containers/Tab/TrendsTab.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: add trendstab file

---

src/pages/cluster/containers/Cluster/actions/Registry.jsx
src/pages/cluster/containers/Template/plugin/actions/Create.jsx

Fixes #
```
```
```release-note
```
```docs
```

fix: fix template data init failed

---

src/containers/Tab/index.jsx
src/pages/cluster/containers/Template/index.jsx

Fixes #
```
```
```release-note
```
```docs
```

fix: fix template tab default active not set

---

src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx

Fixes #
```
```
```release-note
```
```docs
```

fix: fix containerruntime display in cluster detail

---

src/pages/cluster/containers/Template/index.jsx
src/pages/cluster/containers/Template/plugin/actions/Create.jsx

Fixes #
```
```
```release-note
```
```docs
```

fix: fix template active tab err

---

src/components/FormRender/widgets/KSPlugins/index.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: edit pugin data without backfill

---

config/webpack.prod.js
src/components/ErrorBoundary/index.jsx
src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx

Fixes #
```
```
```release-note
```
```docs
```

fix: fix Registries null triger js error

---

src/components/FormRender/widgets/KSPlugins/index.jsx
src/locales/en.json
src/locales/zh.json
src/pages/cluster/components/plugin/PluginForm.jsx
src/pages/cluster/components/plugin/RenderForm.jsx
src/pages/cluster/components/plugin/StorageForm.jsx
src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: use template can not be edited

---

src/core/App.jsx

Fixes #
```
```
```release-note
```
```docs
```

fix: remove errorbounadry outside router

---

src/pages/cluster/containers/Cluster/actions/ScheduledBackup.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: add scheduled backup tip error in cluster dashboard

---

src/stores/templates.js

Fixes #
```
```
```release-note
```
```docs
```

fix: fix template api path

---

src/containers/List/index.jsx
src/pages/cluster/containers/Cluster/index.jsx
src/pages/cluster/containers/Hosting/actions/Create.jsx
src/pages/cluster/containers/Hosting/index.jsx
src/pages/node/containers/Node/index.jsx

Fixes #
```
```
```release-note
```
```docs
```

feat: cluster hosting add project

---

src/pages/cluster/components/plugin/AddPlugin.jsx
src/pages/cluster/components/plugin/AddStorage.jsx
src/pages/cluster/components/plugin/StorageForm.jsx
src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: storage used failed & modify cinder base64

---

.dockerignore
Dockerfile
docker/Caddyfile

Issue: 153916
Fixes #
```
```
```release-note
```
```docs
```

feat: modify dockerfile

---

.github/workflows/build-image.yml
Dockerfile

Signed-off-by: lixd <xueduan.li@gmail.com>
/kind workflow
feat: add workflow to build console image
Fixes #
```
build image when commit
```
```release-note
None
```
```docs
```

feat: add workflow

---

.github/workflows/build-image.yaml
.github/workflows/e2e-test.yml
.gitignore
config/webpack.e2e.js
cypress.config.js
cypress/config/config.yaml

Fixes #
```
```
```release-note
```
```docs
```

ci: adjust e2e workflow

---

cypress/support/e2e.js

Fixes #
```
```
```release-note
```
```docs
```

fix: fix remove import

---

cypress/README.md
cypress/support/commands.js

Fixes #
```
```
```release-note
```
```docs
```

docs: add Cypress Command Introduction

---

cypress.config.js
cypress/README.md
cypress/e2e/pages/access/oauth2.cy.js
cypress/support/commands.js
src/pages/oauth/containers/Login/oauth.jsx
tools/test_cases_associated.js

/kind feature
Fixes #
```
```
```release-note
```
```docs
```

feat: add e2e case about oauth2

---

cypress.config.js
cypress/README.md
cypress/e2e/pages/access/platform-user-role.cy.js
cypress/support/e2e.js
cypress/support/form-commands.js
cypress/support/resource.js
cypress/support/table-commands.js
cypress/utils/index.js
src/components/Tables/Base/ItemAction/DropdownActions.jsx
src/components/Tabs/index.jsx

Fixes #
```
```
```release-note
```
```docs
```

feat: add access e2e cases

---

cypress/e2e/pages/access/platform-user-role.cy.js
cypress/support/detail-command.js
cypress/support/e2e.js
cypress/support/form-commands.js
cypress/support/resource.js
cypress/support/table-commands.js
src/containers/TabDetail/index.jsx

Fixes #
```
```
```release-note
```
```docs
```

feat: add access test cases

---

src/pages/cluster/components/SelectNodes/index.jsx
src/pages/cluster/containers/Cluster/Detail/NodesList/actions/Add.jsx
src/pages/cluster/containers/Cluster/actions/Create/Node.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: nodestore instance error

---

cypress.config.js
cypress/e2e/pages/node/node.cy.js

Signed-off-by: cmyscoups chen.mengyun@99cloud.net

fix: adjust node test cases

---

cypress.config.js
cypress/README.md
cypress/config/config.yaml
cypress/e2e/pages/cluster/backup.cy.js
cypress/e2e/pages/cluster/cluster.cy.js
cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
cypress/e2e/pages/cluster/template.cy.js
cypress/support/table-commands.js

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: modify e2e case for cluster

---

cypress/config/config.yaml
cypress/e2e/pages/cluster/cluster.cy.js
cypress/support/form-commands.js

Fixes #
```
```
```release-note
```
```docs
```

feat: add case test log modal

---

cypress/config/config.yaml
cypress/e2e/pages/access/oauth2.cy.js
cypress/e2e/pages/cluster/cluster.cy.js
cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
cypress/support/commands.js

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: e2e cases error

---

cypress/e2e/pages/cluster/cluster.cy.js
cypress/e2e/pages/cluster/template.cy.js

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: e2e case error

---

cypress/e2e/pages/cluster/cluster.cy.js
cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
cypress/support/detail-command.js
cypress/support/resource.js
cypress/support/table-commands.js
tools/test_cases_associated.js

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: e2e case timeout

---

.github/workflows/full-e2e-test.yml

Signed-off-by: sacredartr <zhou.hao@99cloud.net>
```docs
add openstack rebuild
```

feat: add openstack rebuild

---

src/components/Tables/Base/ActionButton/index.jsx
src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/BackupPoint/actions/Delete.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: modify tip for delete backup space

---

tools/test_cases_associated.js

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: e2e summary resource

---

.github/workflows/full-e2e-test.yml

Signed-off-by: sacredartr <zhou.hao@99cloud.net>

fix: github e2e workflow add screenshots

---

.github/workflows/release.yml

Fixes #
```
```
```release-note
```
```docs
```

fix: fix release action node version

---

src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
src/pages/cluster/containers/Cluster/actions/Create/index.jsx
src/stores/base.js
src/stores/templates.js

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: project data is not updated timely

---

.github/workflows/full-e2e-test.yml

Signed-off-by: sacredartr <zhou.hao@99cloud.net>

fix: remove assets and screenshots before scp

---

cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
cypress/e2e/pages/cluster/template.cy.js

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: modify e2e cases

---

src/resources/cluster.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: modify default value for create cluster

---

src/pages/cluster/containers/Cluster/actions/Create/index.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx

Fixes #
```
```
```release-note
```
```docs
```

fix: the params for create cluster

---

.github/workflows/buid.yaml
.github/workflows/release.yml
.github/workflows/unit-test.yml

Signed-off-by: sacredartr <zhou.hao@99cloud.net>

fix: modify node version

---

cypress.config.js
cypress/e2e/pages/cluster/cluster.cy.js
cypress/support/commands.js
cypress/support/resource.js
src/containers/BaseDetail/index.jsx

Fixes #
```
```
```release-note
```
```docs
```

feat: add cluster e2e cases

---

src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
src/pages/cluster/containers/Cluster/actions/Create/index.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/index.jsx
src/utils/object.mapper.js

/kind feature
Fixes #
```
```
```release-note
```
```docs
```

feat: add CaCert for create cluster

---

src/pages/cluster/containers/Cluster/actions/Create/index.jsx
src/pages/cluster/containers/Cluster/actions/SaveAsTemplate.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: base64 CaCert for create cluster

---

src/components/Tables/Base/ActionButton/index.jsx
src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/BackupPoint/actions/Delete.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: delete backup space

---

src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/Cluster/Detail/Operation/actions/Retry.jsx
src/pages/cluster/containers/Cluster/Detail/Operation/actions/Stop.jsx
src/pages/cluster/containers/Cluster/Detail/Operation/actions/index.jsx
src/resources/cluster.jsx
src/stores/operation.js
src/utils/object.mapper.js

/kind feature
Fixes #
```
```
```release-note
```
```docs
```

feat: stop during runtime

---

src/pages/cluster/components/plugin/AddPlugin.jsx
src/pages/cluster/components/plugin/AddStorage.jsx
src/pages/cluster/containers/Cluster/actions/Create/index.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: adaptive v1.24 for create cluster

---

src/pages/cluster/components/plugin/AddPlugin.jsx
src/pages/cluster/components/plugin/PluginForm.jsx
src/pages/cluster/components/plugin/uiSchemas.js
src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx
src/utils/object.mapper.js

/kind feature
Fixes #
```
```
```release-note
```
```docs
```

feat: add metalb plugin

---

src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/Cluster/actions/Create/Node.jsx
src/pages/cluster/containers/Cluster/actions/Create/index.jsx

/kind feature
Fixes #
```
```
```release-note
```
```docs
```

feat: add cluster node name for create cluster

---

src/stores/root.js
src/stores/template.js

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: start error

---

src/core/menu.js
src/core/routes.js
src/pages/audit/App.jsx
src/pages/audit/containers/LoginLog/index.jsx
src/pages/audit/containers/OperationLog/index.jsx
src/pages/audit/routes/index.js
src/resources/audit.js
src/stores/audit.js
src/stores/root.js

Issue: 162314
Fixes #
```
```
```release-note
```
```docs
```

feat: add audit module

---

cypress.config.js
cypress/e2e/pages/access/oauth2.cy.js
cypress/e2e/pages/access/platform-user-role.cy.js
cypress/e2e/pages/base/header.cy.js
cypress/e2e/pages/cluster/backup.cy.js
cypress/e2e/pages/cluster/cluster.cy.js
cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
cypress/e2e/pages/cluster/online-offline-install.cy.js
cypress/e2e/pages/cluster/registry.cy.js
cypress/e2e/pages/cluster/template.cy.js
cypress/e2e/pages/node/node.cy.js
cypress/e2e/pages/region/region.cy.js
cypress/support/commands.js
cypress/support/resource.js
src/locales/en.json
src/locales/zh.json

Fixes #
```
```
```release-note
```
```docs
```

feat: add cypress test

---

src/pages/cluster/components/plugin/AddPlugin.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: can not add plugin repeat by unique

---

cypress.config.js
cypress/config/config-cluster.yaml
cypress/config/config-others.yaml
cypress/config/config.yaml
cypress/plugins/index.js

Fixes #
```
```
```release-note
```
```docs
```

perf: split e2e case

---

cypress/config/config.yaml
cypress/support/resource.js

Fixes #
```
```
```release-note
```
```docs
```

fix: fix e2e case & set default language to en

---

.github/workflows/full-e2e-test.yml
cypress/e2e/pages/cluster/template.cy.js

Fixes #
```
```
```release-note
```
```docs
```

feat: split e2e test in workflow

---

.github/workflows/full-e2e-test.yml

Fixes #
```
```
```release-note
```
```docs
```

feat: update merge-report file

---

cypress/support/commands.js

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: set default language to en

---

.github/workflows/full-e2e-test.yml

Fixes #
```
```
```release-note
```
```docs
```

feat: use secret for node ip

---

.github/workflows/full-e2e-test.yml
cypress/config/config-backup.yaml
cypress/config/config-cluster.yaml
cypress/config/config.yaml
cypress/e2e/pages/cluster/backup.cy.js
cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
cypress/support/commands.js

Fixes #
```
```
```release-note
```
```docs
```

feat: update e2e test in workflow

---

.github/workflows/full-e2e-test.yml
cypress/config/config-backup.yaml
cypress/config/config-cluster.yaml
cypress/config/config-online.yaml

Fixes #
```
```
```release-note
```
```docs
```

feat: use secret for docs node in e2e workflow

---

cypress/e2e/pages/cluster/backup.cy.js

Fixes #
```
```
```release-note
```
```docs
```

fix: modify backup waiting time

---

src/components/FormItem/index.jsx
src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/Cluster/actions/Create/Cluster.jsx
src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
src/pages/cluster/containers/Cluster/actions/Create/index.jsx
src/pages/cluster/containers/Cluster/actions/Edit.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Confirm.jsx
src/utils/validate.js

/kind feature
Fixes #395
```
```
```release-note
```
```docs
```

feat: add external domain&domainPort for create cluster (#394)

---

src/pages/cluster/containers/Cluster/actions/Create/index.jsx
src/pages/cluster/containers/Cluster/actions/Edit.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: fix externaldomain for create cluster

---

src/pages/cluster/components/SelectNodes/index.less

Fixes #
```
```
```release-note
```
```docs
```

fix: select node css

---

build.sh
config/apps.config.dev.js
config/apps.config.prod.js
config/apps.env.js
config/webpack.dev.js
config/webpack.e2e.js
config/webpack.prod.js
package.json
src/core/i18n.js
src/core/index.common.js
src/core/index.dev.js
src/core/index.prod.js
src/core/routes.js
src/layouts/Blank/index.less
src/layouts/Blank/microContent.jsx
src/layouts/Blank/microHeader.jsx
src/locales/en.json
src/locales/zh.json
src/pages/cluster/containers/Cluster/actions/WorkLoad.jsx
src/pages/cluster/containers/Cluster/actions/index.jsx
src/pages/oauth/containers/Login/index.jsx
src/stores/index.js
src/utils/request.js
yarn.lock

/kind feature
Fixes #
```
```
```release-note
```
```docs
```

feat: add workload for cluser (pro)

---

src/pages/cluster/components/plugin/AddPlugin.jsx
src/pages/cluster/components/plugin/PluginForm.jsx
src/pages/cluster/containers/Cluster/actions/Create/Confirm.jsx
src/pages/cluster/containers/Template/cluster/actions/Create/Cluster.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: monitoring template data change

---

src/pages/cluster/containers/Cluster/Detail/BaseDetail/index.jsx
src/pages/cluster/containers/Cluster/Detail/index.jsx
src/resources/cluster.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: modify cluster name -> display name

---

.github/workflows/buid.yaml

Fixes #
```
```
```release-note
```
```docs
```

fix: add kube dist on kc-console

---

.github/workflows/buid.yaml
config/webpack.dev.js

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: modify build aciton

---

.github/workflows/buid.yaml
.github/workflows/release.yml
.github/workflows/unit-test.yml

update yarn config
/kind documentation
Fixes #
```
None
```
```release-note
None
```
```docs
None
```

build: update github action

---

.github/workflows/buid.yaml
.github/workflows/release.yml

/kind documentation
Fixes #
```
None
```
```release-note
None
```
```docs
None
```

ci: update workflows
